#ifndef PWM_FAN_CONF_H
#define PWM_FAN_CONF_H

// thank you GPT
#define TACHO_PULSE_PER_REV 2
#define TACHO_STOPPED_THRESHOLD 500
#define PWM_FAN_CALIBRATION_DELAY 11000
#define PWM_FAN_CALIBRATION_INIT_DELAY 3000

#endif //PWM_FAN_CONF_H
