#ifndef PWM_FAN_CONF_H
#define PWM_FAN_CONF_H

// thank you GPT
#define TACHO_PULSE_PER_REV 2
#define TACHO_STOPPED_THRESHOLD 200000.0f
#define PWM_FAN_CALIBRATION_PERIOD 500000

#endif //PWM_FAN_CONF_H
